server:
  port: 8000
spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379
  mobile:
    devicedelegatingviewresolver:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
kafka:
  bootstrapAddress: localhost:29092
  topic:
    click: fastgrill.click
