server:
  port: 8000
spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-address: localhost:29092 #  TODO: 각 멀티 프로젝트 별로 정의되도록 변경
    application-id: fast-grill-consumer #  TODO: 각 멀티 프로젝트 별로 정의되도록 변경
    topic:
      impression: fastgrill.impression
      click: fastgrill.click
      conversion: fastgrill.conversion
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

